### ISSUE TITLE
Firefox Compatibility

### ISSUE THREAD

**Issue by gavinhenderson** [sadboyzvone/passthief-modules#6]
@sadboyzvone I've been looking into adding FireFox support. You have any idea how to do it? I have figured out that they store all of the encrypted data in a JSON file but store all the decryption keys in 'key3.db' but I can't for the life of me figure out what database format the file is in (its not SQLite). Any thoughts on how to do it?

**Comment by sadboyzvone** [comment]
Yeah..you have to use their libnss

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sadboyzvone** [comment]
The problem is that you cant use 64bit python on 32bit firefox and vice versa

Sent from ProtonMail mobile

-------- Original Message --------
