### ISSUE TITLE
Chromium based Browsers

### ISSUE THREAD

**Issue by gavinhenderson** [sadboyzvone/passthief-modules#7]
Opera and Chrome are both Chromium based browsers so the recovery method is exactly the same for these browsers and any other chromium browser. 

Work could be done to stop code duplication and add a lot more browsers in one.

**Comment by gavinhenderson** [comment]
@sadboyzvone Feel free to just assign me to this issue

**Comment by sadboyzvone** [comment]
Hey @gavinhenderson feel free to start working whenever you can
